reset "errorreported"
oscar-system/libsingular-julia pull request #28
Opened 2021-05-06 12:12 UTC by hannes14

setting Werror_callback to routines which reset (beside printing the error) also "errorreported"

2021-05-06 15:34 UTC, tthsqe12 requested changes

2021-05-06 15:34 UTC, tthsqe12 commented on singular.cpp
> +    fflush(stderr);
Just writing this to stderr is not the most useful for julia users. How about adding a global variable
```
std::string error_for_julia;
```
then changing this code to
```
static void WerrorS_and_reset(const char * s)
{
    errorreported = 0;
    error_for_julia += s;
}
```
and finally adding the following methods
```
    Singular.method("have_error", []() {
        return !error_for_julia.empty();
    });

    Singular.method("get_and_clear_error", []() {
        std::string s(std::move(error_for_julia));
        error_for_julia.clear();
        return s;
    });
```
--------------------
With this can have
```
function check_error()
   if libSingular.have_error()
      error(libSingular.get_and_clear_error())
   end
end

function div(x::spoly{T}, y::spoly{T}) where T <: Nemo.FieldElem
   check_parent(x, y)
   R = parent(x)
   GC.@preserve x y R begin
      px = libSingular.p_Copy(x.ptr, R.ptr)
      py = libSingular.p_Copy(y.ptr, R.ptr)
      q = R(libSingular.p_Divide(px, py, R.ptr))
      libSingular.check_error()
      return q
   end
end
```

and it will look like https://github.com/oscar-system/Singular.jl/issues/368

2021-05-07 09:48 UTC, tthsqe12 commented
@hannes14 Thanks for the suggested changes. I will work them into a separate PR that can be tested along with singular.jl

2021-05-07 09:57 UTC, hannes14 reviewed
We can use the already existing "singular-error".
But keep in mind, that every call to libsingular may call Werror and produce an error message,
which is not printed, if not checked for.

2021-05-07 10:01 UTC, tthsqe12 commented
Ok. The idea is to turn the errors into julia errors, but I will keep the printing to stderror so we can at least see when we have a missing `libSingular.check_error()`.

2021-05-07 11:19 UTC, tthsqe12 commented
done in https://github.com/oscar-system/libsingular-julia/pull/29

2021-05-07 11:19 UTC, closed without merging